/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 27 20:50:55 GMT 2023
 */

package org.apache.commons.mail;

import org.junit.Test;
import static org.junit.Assert.*;
import javax.mail.PasswordAuthentication;
import org.apache.commons.mail.DefaultAuthenticator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DefaultAuthenticator_ESTest extends DefaultAuthenticator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultAuthenticator defaultAuthenticator0 = new DefaultAuthenticator("", "");
      PasswordAuthentication passwordAuthentication0 = defaultAuthenticator0.getPasswordAuthentication();
      assertNotNull(passwordAuthentication0);
  }
}
