/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Jun 27 20:32:29 GMT 2023
 */

package org.apache.commons.mail.util;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class MimeMessageParser_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  protected static ExecutorService executor; 

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.mail.util.MimeMessageParser"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    executor = Executors.newCachedThreadPool(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    executor.shutdownNow(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/nm/9k1qd0l12h9_56_0pzt237qc0000gn/T/"); 
    java.lang.System.setProperty("user.country", "IT"); 
    java.lang.System.setProperty("user.dir", "/Users/antonio/Documents/GitHub/commons-email-mod"); 
    java.lang.System.setProperty("user.home", "/Users/antonio"); 
    java.lang.System.setProperty("user.language", "it"); 
    java.lang.System.setProperty("user.name", "antonio"); 
    java.lang.System.setProperty("user.timezone", "Europe/Rome"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MimeMessageParser_ESTest_scaffolding.class.getClassLoader() ,
      "net.sf.saxon.expr.ContextItemExpression",
      "net.sf.saxon.expr.PromotionOffer",
      "org.codehaus.plexus.util.InterpolationFilterReader",
      "net.sf.saxon.event.Sender",
      "net.sf.saxon.om.NamePool$NamePoolLimitException",
      "net.sf.saxon.event.StandardOutputResolver",
      "net.sf.saxon.event.UnicodeNormalizer",
      "org.codehaus.plexus.DefaultPlexusContainer",
      "org.codehaus.classworlds.NoSuchRealmException",
      "org.codehaus.plexus.context.DefaultContext$Hidden",
      "net.sf.saxon.query.QueryModule",
      "net.sf.saxon.type.TypeHierarchy",
      "net.sf.saxon.trans.Mode",
      "org.codehaus.plexus.component.configurator.ComponentConfigurationException",
      "net.sf.saxon.trans.CompilerInfo",
      "net.sf.saxon.expr.PathMap",
      "net.sf.saxon.type.ConversionResult",
      "net.sf.saxon.om.NamePool",
      "net.sf.saxon.type.ItemType",
      "net.sf.saxon.dom.DOMObjectModel$3",
      "net.sf.saxon.value.NumericValue",
      "net.sf.saxon.dom.DOMObjectModel$4",
      "net.sf.saxon.dom.DOMObjectModel$1",
      "net.sf.saxon.dom.DOMObjectModel$2",
      "net.sf.saxon.charcode.CharacterSetFactory",
      "net.sf.saxon.dom.DOMObjectModel$5",
      "org.apache.commons.mail.util.MimeMessageParser",
      "net.sf.saxon.om.NameChecker",
      "net.sf.saxon.tinytree.CharSlice",
      "net.sf.saxon.functions.ExtensionFunctionFactory",
      "net.sf.saxon.event.UncommittedSerializer",
      "net.sf.saxon.sort.IntSet",
      "net.sf.saxon.expr.PendingUpdateList",
      "net.sf.saxon.expr.PathMap$PathMapNodeSet",
      "net.sf.saxon.value.Whitespace",
      "net.sf.saxon.charcode.UnknownCharacterSet",
      "net.sf.saxon.event.IDFilter",
      "net.sf.saxon.value.EmptySequence",
      "net.sf.saxon.instruct.SlotManager",
      "net.sf.saxon.expr.RoleLocator",
      "net.sf.saxon.evpull.PullEventSource",
      "net.sf.saxon.event.Receiver",
      "org.codehaus.plexus.logging.Logger",
      "net.sf.saxon.StandardURIResolver",
      "net.sf.saxon.trans.DynamicLoader",
      "net.sf.saxon.event.LocationProvider",
      "net.sf.saxon.value.QualifiedNameValue",
      "net.sf.saxon.event.SaxonLocator",
      "org.codehaus.classworlds.ClassWorldException",
      "net.sf.saxon.instruct.Executable",
      "net.sf.saxon.pattern.NodeTest",
      "org.codehaus.classworlds.BytesURLConnection",
      "net.sf.saxon.event.XMLIndenter",
      "org.codehaus.plexus.component.configurator.BasicComponentConfigurator",
      "org.codehaus.plexus.component.factory.UndefinedComponentFactoryException",
      "net.sf.saxon.value.Base64BinaryValue",
      "net.sf.saxon.functions.ExtensionFunctionCall",
      "net.sf.saxon.functions.Evaluate$PreparedExpression",
      "net.sf.saxon.charcode.CharacterSet",
      "org.codehaus.classworlds.BytesURLStreamHandler",
      "net.sf.saxon.om.ExternalObjectModel",
      "net.sf.saxon.expr.Literal",
      "net.sf.saxon.OutputURIResolver",
      "net.sf.saxon.event.ProxyReceiver",
      "net.sf.saxon.event.TreeReceiver",
      "net.sf.saxon.instruct.GlobalVariable",
      "net.sf.saxon.sort.NamedCollation",
      "net.sf.saxon.event.XML10ContentChecker",
      "org.codehaus.plexus.component.configurator.ComponentConfigurator",
      "net.sf.saxon.event.Stripper",
      "net.sf.saxon.type.ValidationException",
      "org.codehaus.plexus.component.composition.UndefinedComponentComposerException",
      "org.codehaus.plexus.component.configurator.AbstractComponentConfigurator",
      "org.codehaus.plexus.configuration.processor.ConfigurationResourceHandler",
      "net.sf.saxon.om.AllElementStripper",
      "net.sf.saxon.dom.DOMEnvelope$3",
      "net.sf.saxon.dom.DOMEnvelope$1",
      "net.sf.saxon.dom.DOMEnvelope$2",
      "net.sf.saxon.expr.BinaryExpression",
      "net.sf.saxon.dom.DOMObjectModel",
      "net.sf.saxon.query.XQueryFunctionBinder",
      "org.codehaus.classworlds.UrlUtils",
      "net.sf.saxon.Platform",
      "net.sf.saxon.sort.IntHashSet",
      "org.codehaus.plexus.component.manager.ComponentManager",
      "net.sf.saxon.expr.FunctionCall",
      "net.sf.saxon.TransformerFactoryImpl",
      "net.sf.saxon.om.Name10Checker",
      "net.sf.saxon.pull.PullSource",
      "org.codehaus.plexus.configuration.PlexusConfiguration",
      "net.sf.saxon.event.SerializerFactory",
      "net.sf.saxon.trace.InstructionInfo",
      "net.sf.saxon.trace.TraceListener",
      "net.sf.saxon.pattern.NameTest",
      "net.sf.saxon.functions.CompileTimeFunction",
      "net.sf.saxon.trans.XPathException",
      "net.sf.saxon.type.SimpleType",
      "net.sf.saxon.event.SequenceReceiver",
      "net.sf.saxon.om.NamePool$NameEntry",
      "net.sf.saxon.exslt.Common",
      "net.sf.saxon.sort.NodeOrderComparer",
      "net.sf.saxon.event.ParseOptions",
      "net.sf.saxon.type.SchemaURIResolver",
      "net.sf.saxon.om.ValueRepresentation",
      "net.sf.saxon.instruct.TailCall",
      "net.sf.saxon.event.XMLEmitter",
      "net.sf.saxon.PreparedStylesheet",
      "net.sf.saxon.event.Emitter",
      "net.sf.saxon.value.IntegerValue",
      "net.sf.saxon.event.XQueryEmitter",
      "org.apache.commons.mail.DefaultAuthenticator",
      "net.sf.saxon.om.NamespaceConstant",
      "org.codehaus.plexus.component.repository.ComponentDescriptor",
      "net.sf.saxon.evpull.EventIterator",
      "net.sf.saxon.expr.CollationMap",
      "net.sf.saxon.SourceResolver",
      "net.sf.saxon.pattern.NodeKindTest",
      "net.sf.saxon.event.HTMLIndenter",
      "org.codehaus.plexus.context.DefaultContext",
      "net.sf.saxon.instruct.Template",
      "net.sf.saxon.value.CalendarValue",
      "net.sf.saxon.instruct.LocationMap",
      "net.sf.saxon.expr.Binding",
      "net.sf.saxon.functions.FunctionLibrary",
      "net.sf.saxon.functions.URIQueryParameters",
      "net.sf.saxon.om.NamespaceResolver",
      "net.sf.saxon.instruct.TerminationException",
      "net.sf.saxon.instruct.GeneralVariable",
      "net.sf.saxon.query.ModuleURIResolver",
      "net.sf.saxon.expr.EvaluableItem",
      "net.sf.saxon.NonDelegatingURIResolver",
      "net.sf.saxon.trans.NoDynamicContextException",
      "net.sf.saxon.event.SequenceOutputter",
      "net.sf.saxon.value.SequenceType",
      "net.sf.saxon.trans.UnparsedTextURIResolver",
      "net.sf.saxon.trans.XPathException$Circularity",
      "org.codehaus.classworlds.RealmClassLoader",
      "net.sf.saxon.expr.PJConverter",
      "org.codehaus.classworlds.ClassRealm",
      "net.sf.saxon.exslt.Date",
      "net.sf.saxon.instruct.Instruction",
      "org.codehaus.plexus.configuration.PlexusConfigurationException",
      "org.codehaus.classworlds.DuplicateRealmException",
      "net.sf.saxon.expr.StaticContext",
      "org.codehaus.plexus.logging.AbstractLogEnabled",
      "net.sf.saxon.IdentityTransformer",
      "net.sf.saxon.expr.PathMap$PathMapRoot",
      "net.sf.saxon.instruct.Bindery",
      "net.sf.saxon.value.DoubleValue",
      "org.codehaus.plexus.configuration.PlexusConfigurationResourceException",
      "net.sf.saxon.event.TEXTEmitter",
      "net.sf.saxon.sort.SortKeyEvaluator",
      "net.sf.saxon.java.JavaPlatform",
      "org.codehaus.plexus.PlexusContainerException",
      "net.sf.saxon.functions.JavaExtensionFunctionFactory",
      "net.sf.saxon.evpull.PullEvent",
      "org.codehaus.plexus.component.composition.CompositionException",
      "net.sf.saxon.sort.StandardCollationURIResolver",
      "net.sf.saxon.expr.XPathContextMinor",
      "net.sf.saxon.event.SaxonOutputKeys",
      "net.sf.saxon.event.XHTMLEmitter",
      "net.sf.saxon.expr.XPathContextMajor",
      "net.sf.saxon.type.AtomicType",
      "net.sf.saxon.om.DocumentInfo",
      "net.sf.saxon.expr.Expression",
      "net.sf.saxon.om.QNameException",
      "net.sf.saxon.trans.DecimalFormatManager",
      "net.sf.saxon.om.DocumentNumberAllocator",
      "net.sf.saxon.expr.Optimizer",
      "net.sf.saxon.functions.SystemFunction",
      "net.sf.saxon.value.SequenceExtent",
      "net.sf.saxon.trans.StandardUnparsedTextResolver",
      "org.codehaus.plexus.component.factory.ComponentInstantiationException",
      "org.codehaus.classworlds.UberJarRealmClassLoader",
      "org.codehaus.plexus.logging.LoggerManager",
      "net.sf.saxon.event.Builder",
      "net.sf.saxon.event.HTMLEmitter",
      "net.sf.saxon.tinytree.TinyBuilder",
      "net.sf.saxon.expr.JPConverter",
      "net.sf.saxon.om.GroundedValue",
      "org.codehaus.plexus.component.manager.UndefinedComponentManagerException",
      "net.sf.saxon.om.StructuredQName",
      "net.sf.saxon.type.SchemaDeclaration",
      "org.codehaus.plexus.context.ContextException",
      "org.codehaus.plexus.context.DefaultContext$1",
      "net.sf.saxon.exslt.Sets",
      "net.sf.saxon.expr.ExpressionParser",
      "net.sf.saxon.functions.JavaExtensionLibrary",
      "net.sf.saxon.sort.IntIterator",
      "net.sf.saxon.expr.ExpressionVisitor",
      "org.codehaus.plexus.DuplicateChildContainerException",
      "net.sf.saxon.expr.SequenceIterable",
      "net.sf.saxon.event.StartTagBuffer",
      "net.sf.saxon.instruct.Procedure",
      "org.codehaus.plexus.logging.LogEnabled",
      "net.sf.saxon.value.AtomicValue",
      "net.sf.saxon.functions.FunctionLibraryList",
      "net.sf.saxon.value.DateTimeValue",
      "net.sf.saxon.value.Value",
      "net.sf.saxon.type.SchemaException",
      "net.sf.saxon.functions.VendorFunctionLibrary",
      "net.sf.saxon.functions.JavaExtensionLibrary$UnresolvedExtensionFunction",
      "net.sf.saxon.expr.XPathContext",
      "net.sf.saxon.CollectionURIResolver",
      "net.sf.saxon.expr.MappingFunction",
      "org.codehaus.plexus.component.repository.exception.ComponentRepositoryException",
      "net.sf.saxon.sort.IntHashMap",
      "net.sf.saxon.expr.Container",
      "net.sf.saxon.type.SchemaComponent",
      "net.sf.saxon.om.Name11Checker",
      "org.codehaus.classworlds.ClassWorld",
      "net.sf.saxon.dom.DOMEnvelope",
      "net.sf.saxon.query.XQueryExpression",
      "net.sf.saxon.Configuration",
      "net.sf.saxon.trans.RuleManager",
      "net.sf.saxon.event.PipelineConfiguration",
      "org.codehaus.plexus.component.repository.exception.ComponentLifecycleException",
      "net.sf.saxon.value.QNameValue",
      "net.sf.saxon.value.SingletonNode",
      "net.sf.saxon.charcode.UnicodeCharacterSet",
      "net.sf.saxon.value.DecimalValue",
      "net.sf.saxon.type.SchemaType",
      "org.codehaus.plexus.lifecycle.UndefinedLifecycleHandlerException",
      "net.sf.saxon.exslt.Math",
      "net.sf.saxon.trans.KeyManager",
      "net.sf.saxon.exslt.Random",
      "net.sf.saxon.dom.DOMSender",
      "org.codehaus.plexus.configuration.processor.ConfigurationResourceNotFoundException",
      "net.sf.saxon.om.Item",
      "net.sf.saxon.event.CharacterMapExpander",
      "net.sf.saxon.regex.RegularExpression",
      "net.sf.saxon.event.CDATAFilter",
      "net.sf.saxon.event.ContentHandlerProxy",
      "net.sf.saxon.Controller",
      "net.sf.saxon.event.SequenceWriter",
      "net.sf.saxon.instruct.Debugger",
      "org.codehaus.plexus.component.discovery.ComponentDiscoveryListener",
      "net.sf.saxon.sort.StringCollator",
      "org.codehaus.plexus.context.Context",
      "net.sf.saxon.event.SourceLocationProvider",
      "net.sf.saxon.value.BooleanValue",
      "net.sf.saxon.sort.CollationURIResolver",
      "net.sf.saxon.expr.IdentityComparison",
      "net.sf.saxon.om.SequenceIterator",
      "org.codehaus.plexus.component.repository.exception.ComponentLookupException",
      "net.sf.saxon.StandardErrorListener",
      "org.codehaus.plexus.configuration.processor.ConfigurationProcessingException",
      "net.sf.saxon.tree.TreeBuilder",
      "net.sf.saxon.om.DocumentPool",
      "net.sf.saxon.instruct.GlobalParameterSet",
      "net.sf.saxon.om.NodeInfo",
      "net.sf.saxon.event.NamespaceReducer",
      "net.sf.saxon.expr.PathMap$PathMapNode",
      "net.sf.saxon.charcode.BuggyCharacterSet",
      "org.codehaus.classworlds.DefaultClassRealm",
      "net.sf.saxon.functions.Extensions",
      "org.codehaus.plexus.PlexusContainer",
      "net.sf.saxon.query.StandardModuleURIResolver",
      "net.sf.saxon.expr.ItemMappingFunction",
      "net.sf.saxon.event.XHTMLIndenter",
      "net.sf.saxon.event.MetaTagAdjuster",
      "net.sf.saxon.value.HexBinaryValue",
      "net.sf.saxon.instruct.TailCallReturner",
      "net.sf.saxon.trace.ExpressionPresenter",
      "net.sf.saxon.query.QueryParser",
      "net.sf.saxon.functions.StandardCollectionURIResolver",
      "net.sf.saxon.event.HTMLURIEscaper"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.util.Enumeration", false, MimeMessageParser_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MimeMessageParser_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.mail.util.MimeMessageParser",
      "org.codehaus.classworlds.ClassWorld",
      "org.codehaus.classworlds.DefaultClassRealm",
      "org.codehaus.classworlds.RealmClassLoader",
      "org.codehaus.classworlds.UrlUtils",
      "org.apache.commons.mail.DefaultAuthenticator",
      "net.sf.saxon.TransformerFactoryImpl",
      "net.sf.saxon.java.JavaPlatform",
      "net.sf.saxon.Configuration",
      "net.sf.saxon.StandardURIResolver",
      "net.sf.saxon.sort.StandardCollationURIResolver",
      "net.sf.saxon.functions.StandardCollectionURIResolver",
      "net.sf.saxon.query.StandardModuleURIResolver",
      "net.sf.saxon.om.DocumentNumberAllocator",
      "net.sf.saxon.om.DocumentPool",
      "net.sf.saxon.trans.DynamicLoader",
      "net.sf.saxon.event.SerializerFactory",
      "net.sf.saxon.functions.JavaExtensionFunctionFactory",
      "net.sf.saxon.expr.Expression",
      "net.sf.saxon.expr.FunctionCall",
      "net.sf.saxon.functions.ExtensionFunctionCall",
      "net.sf.saxon.dom.DOMEnvelope",
      "net.sf.saxon.dom.DOMObjectModel",
      "net.sf.saxon.trans.XPathException",
      "net.sf.saxon.om.NamePool",
      "net.sf.saxon.functions.JavaExtensionLibrary",
      "net.sf.saxon.functions.Extensions",
      "net.sf.saxon.exslt.Common",
      "net.sf.saxon.exslt.Sets",
      "net.sf.saxon.exslt.Math",
      "net.sf.saxon.exslt.Date",
      "net.sf.saxon.exslt.Random",
      "net.sf.saxon.Controller",
      "net.sf.saxon.IdentityTransformer",
      "net.sf.saxon.instruct.Executable",
      "net.sf.saxon.instruct.Bindery",
      "net.sf.saxon.event.StandardOutputResolver",
      "net.sf.saxon.trans.StandardUnparsedTextResolver",
      "net.sf.saxon.StandardErrorListener",
      "net.sf.saxon.om.NameChecker",
      "net.sf.saxon.om.Name10Checker",
      "net.sf.saxon.event.SaxonOutputKeys",
      "net.sf.saxon.event.PipelineConfiguration",
      "net.sf.saxon.event.Emitter",
      "net.sf.saxon.event.XMLEmitter",
      "net.sf.saxon.sort.IntHashMap",
      "net.sf.saxon.event.SequenceReceiver",
      "net.sf.saxon.event.ProxyReceiver",
      "net.sf.saxon.event.XMLIndenter",
      "net.sf.saxon.charcode.CharacterSetFactory",
      "net.sf.saxon.charcode.UnicodeCharacterSet",
      "net.sf.saxon.event.NamespaceReducer",
      "net.sf.saxon.event.Sender",
      "net.sf.saxon.event.ParseOptions",
      "net.sf.saxon.dom.DOMSender",
      "net.sf.saxon.om.NamespaceConstant",
      "net.sf.saxon.om.NamePool$NameEntry",
      "net.sf.saxon.tinytree.CharSlice",
      "net.sf.saxon.value.Whitespace",
      "org.codehaus.classworlds.BytesURLStreamHandler",
      "org.codehaus.classworlds.ClassWorldException",
      "org.codehaus.classworlds.DuplicateRealmException",
      "org.codehaus.plexus.logging.AbstractLogEnabled",
      "org.codehaus.plexus.DefaultPlexusContainer",
      "org.codehaus.plexus.context.DefaultContext$Hidden",
      "org.codehaus.plexus.context.DefaultContext"
    );
  }
}
