/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 27 20:51:40 GMT 2023
 */

package org.apache.commons.mail;

import org.junit.Test;
import static org.junit.Assert.*;
import java.net.URL;
import org.apache.commons.mail.EmailAttachment;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EmailAttachment_ESTest extends EmailAttachment_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EmailAttachment emailAttachment0 = new EmailAttachment();
      emailAttachment0.setPath((String) null);
      String string0 = emailAttachment0.getPath();
      assertNull(string0);
      assertEquals("attachment", emailAttachment0.getDisposition());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      EmailAttachment emailAttachment0 = new EmailAttachment();
      emailAttachment0.setPath("(zM5[%pGCG-P+se");
      emailAttachment0.getPath();
      assertEquals("(zM5[%pGCG-P+se", emailAttachment0.getPath());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EmailAttachment emailAttachment0 = new EmailAttachment();
      emailAttachment0.setName((String) null);
      String string0 = emailAttachment0.getName();
      assertEquals("attachment", emailAttachment0.getDisposition());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      EmailAttachment emailAttachment0 = new EmailAttachment();
      emailAttachment0.setName("\"iL`5$?,4EeQ]7z+h%q");
      emailAttachment0.getName();
      assertEquals("\"iL`5$?,4EeQ]7z+h%q", emailAttachment0.getName());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EmailAttachment emailAttachment0 = new EmailAttachment();
      emailAttachment0.setDisposition((String) null);
      String string0 = emailAttachment0.getDisposition();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EmailAttachment emailAttachment0 = new EmailAttachment();
      emailAttachment0.setDescription((String) null);
      String string0 = emailAttachment0.getDescription();
      assertNull(string0);
      assertEquals("attachment", emailAttachment0.getDisposition());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      EmailAttachment emailAttachment0 = new EmailAttachment();
      assertEquals("attachment", emailAttachment0.getDisposition());
      
      emailAttachment0.setDisposition("");
      String string0 = emailAttachment0.getDisposition();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EmailAttachment emailAttachment0 = new EmailAttachment();
      String string0 = emailAttachment0.getDisposition();
      assertEquals("attachment", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      EmailAttachment emailAttachment0 = new EmailAttachment();
      assertEquals("", emailAttachment0.getDescription());
      
      emailAttachment0.setDescription("inline");
      String string0 = emailAttachment0.getDescription();
      assertEquals("inline", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EmailAttachment emailAttachment0 = new EmailAttachment();
      String string0 = emailAttachment0.getDescription();
      assertEquals("attachment", emailAttachment0.getDisposition());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EmailAttachment emailAttachment0 = new EmailAttachment();
      String string0 = emailAttachment0.getPath();
      assertEquals("attachment", emailAttachment0.getDisposition());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EmailAttachment emailAttachment0 = new EmailAttachment();
      emailAttachment0.setURL((URL) null);
      assertEquals("attachment", emailAttachment0.getDisposition());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      EmailAttachment emailAttachment0 = new EmailAttachment();
      emailAttachment0.getURL();
      assertEquals("attachment", emailAttachment0.getDisposition());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      EmailAttachment emailAttachment0 = new EmailAttachment();
      String string0 = emailAttachment0.getName();
      assertEquals("", string0);
      assertEquals("attachment", emailAttachment0.getDisposition());
  }
}
